# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test.proto for package 'test'

require 'grpc'
require_relative 'test_pb'

module Test
  module Test
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'test.Test'

      rpc :ListFoos, ::Test::ListFoosRequest, stream(::Test::Foo)
      rpc :CreateFoos, stream(::Test::CreateFoosRequest), ::Test::EmptyResp
      rpc :TradeFoos, stream(::Test::Foo), stream(::Test::Bar)
    end

    Stub = Service.rpc_stub_class
  end
end
